### ISSUE TITLE
Application not responding for invalid credentials and if MQ service is down

### ISSUE THREAD

**Issue by karthim20** [Havret/dotnet-activemq-artemis-client#266]
Application not responding for invalid username/password and if MQ service is down

**Comment by Havret** [comment]
1) When the server is not available, and auto-recovery is enabled on the client, it may give you an impression that the clients freezes. This is a desired behavior. You can use a cancellation token, to provide appropriate timeout for initial connection. It is described in the docs --> https://havret.github.io/dotnet-activemq-artemis-client/docs/auto-recovery
2) When you provide invalid credentials, auto-recovery should not try to reconnect. It will be addressed by #267.

**Comment by Havret** [comment]
The fix is released in version 2.1.2 I've update the extensions as well.
