### ISSUE TITLE
Question - Receiving Messages - acknowledge-mode "transacted"

### ISSUE THREAD

**Issue by rizi** [Havret/dotnet-activemq-artemis-client#288]
Hi,
Our customer told us we have to use the acknowledge-mode "transacted" when receiving messages, can you tell me what this means?

I can't find a way to specify this mode when receiving a message, am I doing something wrong?

Here is a small sample which shows how I receive a message

```
  Endpoint endpoint = Endpoint.Create("localhost", 9898, "test", "test"); 
  ConnectionFactory connectionFactory = new ConnectionFactory();

  await using (IConnection connection = await connectionFactory.CreateAsync(endpoint))
  {

      IConsumer consumer = await connection.CreateConsumerAsync("Test", RoutingType.Anycast);
      Message message = await consumer.ReceiveAsync();

      await consumer.AcceptAsync(message);
  }
```

**Comment by Havret** [comment]
Hi @rizi,

It basically means to use transactions for message acknowledgment. It is especially useful when you consume multiple messages, and you want to be sure that they will be acknowledged in all or nothing manner.

Modifying slightly your example, it may look as follows:

```c#
await using (IConnection connection = await connectionFactory.CreateAsync(endpoint))
{
    IConsumer consumer = await connection.CreateConsumerAsync("Test", RoutingType.Anycast);
    Message msg1 = await consumer.ReceiveAsync();
    Message msg2 = await consumer.ReceiveAsync();

    // start transaction
    await using (var transaction = new Transaction())
    {
        // ack the first message
        await consumer.AcceptAsync(msg1, transaction);
        
        // ack the second message
        await consumer.AcceptAsync(msg2, transaction);

        // commit the transaction
        await transaction.CommitAsync();
        
        // at this point you're sure that both messages were acknowledged

    }
}
```

Of course, this is only a small example. You can do much more with transactions. For more use cases, please checkout transactions spec  --> https://github.com/Havret/dotnet-activemq-artemis-client/blob/master/test/ActiveMQ.Artemis.Client.IntegrationTests/TransactionsSpec.cs

I hope this answers your question.

**Comment by rizi** [comment]
> Hi @rizi,
> 
> It basically means to use transactions for message acknowledgment. It is especially useful when you consume multiple messages, and you want to be sure that they will be acknowledged in all or nothing manner.
> 
> Modifying slightly your example, it may look as follows:
> 
> ```cs
> await using (IConnection connection = await connectionFactory.CreateAsync(endpoint))
> {
>     IConsumer consumer = await connection.CreateConsumerAsync("Test", RoutingType.Anycast);
>     Message msg1 = await consumer.ReceiveAsync();
>     Message msg2 = await consumer.ReceiveAsync();
> 
>     // start transaction
>     await using (var transaction = new Transaction())
>     {
>         // ack the first message
>         await consumer.AcceptAsync(msg1, transaction);
>         
>         // ack the second message
>         await consumer.AcceptAsync(msg2, transaction);
> 
>         // commit the transaction
>         await transaction.CommitAsync();
>         
>         // at this point you're sure that both messages were acknowledged
> 
>     }
> }
> ```
> 
> Of course, this is only a small example. You can do much more with transactions. For more use cases, please check out the transactions spec --> https://github.com/Havret/dotnet-activemq-artemis-client/blob/master/test/ActiveMQ.Artemis.Client.IntegrationTests/TransactionsSpec.cs
> 
> I hope this answers your question.

Thx for the answer, that makes things much more clearer!

Br
