### ISSUE TITLE
Support for consumer filters

### ISSUE THREAD

**Issue by engineering87** [Havret/dotnet-activemq-artemis-client#384]
Consumer filters are applied after messages have reached a queue and are defined using the appropriate client APIs.

https://activemq.apache.org/components/artemis/documentation/2.11.0/address-model.html

**Comment by Havret** [comment]
Hi @engineering87 

You can define filter directly on your consumer:

```csharp
await using var highPriorityConsumer = await connection.CreateConsumerAsync(new ConsumerConfiguration
{
    FilterExpression = "AMQPriority = 9",
    Address = "address",
    Queue = "queue",
    Shared = true,
    Durable = true,
    RoutingType = RoutingType.Multicast,
});
```

Or by pre-configuring queue with the filter using topology manager api:

```csharp
await using var topologyManager = await connection.CreateTopologyManagerAsync();
await topologyManager.CreateQueueAsync(new QueueConfiguration
{
    Address = "address",
    RoutingType = RoutingType.Multicast,
    Name = "queue",
    AutoCreateAddress = true,
    FilterExpression = "AMQPriority = 9"
}, CancellationToken);
var consumer = await connection.CreateConsumerAsync(address, queue);
```

For more details you can check:
- https://github.com/Havret/dotnet-activemq-artemis-client/blob/master/test/ArtemisNetClient.IntegrationTests/FilterExpressionsSpec.cs
- https://github.com/Havret/dotnet-activemq-artemis-client/blob/master/test/ArtemisNetClient.IntegrationTests/TopologyManagement/CreateQueueSpec.cs#L94-L116

Hope that helps,
Havret

**Comment by engineering87** [comment]
Thank you @Havret !
