### ISSUE TITLE
Support for ApplicationProperties, CloudNative.CloudEvents.Amqp

### ISSUE THREAD

**Issue by JinsPeter** [Havret/dotnet-activemq-artemis-client#409]
## Feature description
- Application Messages required Header information to be passed.
- Best practice around Events messaging metadata is CloudEvents,
- Now Artemis.Message does not have setter for application properties.
- Cloudnative CloudEvents are written on top of  AmqpNetLite

## Feature in action
Provide a way to convert Amqp.Message to Artemis.Message. Now it only accepts `BodySection`. All metadata is lost.
Also provide a way to recreate the cloudevent from the ArtemisMessage.

```csharp

          CloudEvent cloudEvent = new CloudEvent(CloudEventsSpecVersion.V1_0)
            {
                Id = cloudEventId,
                Data = m_serializer.SerializeToJson(message),
                DataContentType = "application/json",
                Source = s_eventSource,
                Type = eventType,
                Time = DateTime.UtcNow,
            };

            Amqp.Message amqpMessage = cloudEvent.ToAmqpMessage(ContentMode.Structured, m_cloudEventFormatter);
            Message artemisMessage = new Message(amqpMessage.BodySection);
```

## Additional context
[CloudNative.CloudEvents.NetSDK](https://github.com/cloudevents/sdk-csharp/blob/main/docs/guide.md)  - Please see Amqp.

**Comment by Havret** [comment]
Hi @JinsPeter,

To be honest, it's the first time I hear about CloudEvents, but the idea seems really nice and promising. 

Regarding the implementation, I'm not so sure that exposing a method to transform ArtemisNetClient's message to AmqpNetLite's message would be the way to tackle this issue. The fact that we are using AmqpNetLite internally is just an implementation detail, that may change in the future if any better, faster or more promising implementations of AMQP protocol appear in the dotnet landscape. 

In my humble opinion, CloudEvents spec is simple enough so we could provide a full-blown integration[1] as an extension library to ArtemisNetClient. 

```
CloudEvent cloudEvent = new CloudEvent(CloudEventsSpecVersion.V1_0)
{
    Id = cloudEventId,
    Data = m_serializer.SerializeToJson(message),
    DataContentType = "application/json",
    Source = s_eventSource,
    Type = eventType,
    Time = DateTime.UtcNow,
};

Message artemisMessage = cloudEvent.ToActiveMqMessage();
```

Would sth like that work for you?

I cannot promise a specific date, but I could try to implement it after Christmas.

Best,
Havret

[1] Maybe we could use [CloudNative.CloudEvents.Amqp](https://www.nuget.org/packages/CloudNative.CloudEvents.Amqp) under the hood to streamline the implementation.

**Comment by Havret** [comment]
Please check [ArtemisNetClient.Extensions.CloudEvents 2.12.0-preview1](https://www.nuget.org/packages/ArtemisNetClient.Extensions.CloudEvents/2.12.0-preview1).
