### ISSUE TITLE
Support for WebSocket protocol via AMQPNetLite.WebSockets library

### ISSUE THREAD

**Issue by bassmake** [Havret/dotnet-activemq-artemis-client#457]
## Feature description

The native AMQP protocol is not always achievable in some highly regulated environments with firewalls. Therefore support for WebSocket transport via 80 or 443 ports would be beneficial.

## Feature in action

```csharp
var endpoint = Endpoint.Create("messages.military.com", 132, Scheme.WSS, path: "/redirectMeToBrokerA")
```

## Describe alternatives you've considered
- Using AMQP.Net Lite directly
- Tweaking this library with copy-change-override or reflection magic.

**Comment by Havret** [comment]
Hi @bassmake, it doesn't seem to be too difficult. I will try to implement it over the weekend.

**Comment by Havret** [comment]
Hi @bassmake, could you please check [2.14.0-preview1](https://www.nuget.org/packages/ArtemisNetClient/2.14.0-preview1).

**Comment by bassmake** [comment]
Thank you for very fast feedback.
I've checked preliminary WebSocket support without TLS and it looks good.
Next week we will do more validation.
