### ISSUE TITLE
Subscriptions and scalability on OpenShift

### ISSUE THREAD

**Issue by engineering87** [Havret/dotnet-activemq-artemis-client#466]
Greetings, 
I'm opening this issue to get clarification on the possibility of scaling the same subscription in a containerized environment. The reference environment concerns microservices on OpenShift. Having an anycast Artemis queue we obviously have only one active subscription. However, I would like to understand if there is the possibility of logically scaling this subscription on the pods of the same instance of the consumer microservice and parallelizing the processing.

## Environment:

- OS: OpenShift 4.13
- Version Artemis Client: 2.12
- Broker: ActiveMQ Artemis 2.21.0.redhat-00041

Thank you

**Comment by Havret** [comment]
Hi,

You should find the answer to your question in [this article](https://havret.io/activemq-artemis-address-model). Please refer to the `Anycast Routing Type` section. If any points are unclear, I'm happy to help further.

I hope that helps.

**Comment by engineering87** [comment]
Thank you @Havret
